# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.76

## Mod Properties
mod_id=minefantasyreforged
mod_name=MineFantasy Reforged
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=minefantasy.mfr
mod_authors=ThatPolishKid99,SkuldNorniern
mod_description=A medieval-fantasy themed soft total conversion, focused around the themes of Blacksmithing and Medieval Combat

# Publishing
github=SkuldNorniern/MineFantasyReforged
curse_project_id=431996
